parameters:
  sisapi.auth_module.class: UBC\SISAPI\Authentication\Auth2
# sisapi.auth_module.class: UBC\SISAPI\Authentication\Basic
  sisapi.config.base_url: http://sisapi.example.com
  sisapi.config.username: service_username
  sisapi.config.password: service_password
  sisapi.config.service_url: http://auth2.example.com
  sisapi.config.service_application: test_app

services:
  sisapi.config:
    class: UBC\SISAPI\Service\Config
    arguments: ["%sisapi.config.base_url%", "%sisapi.config.username%", "%sisapi.config.password%"]

  sisapi.http_client:
    class: UBC\SISAPI\HttpClient\GuzzleClient
    lazy: true

  sisapi.serializer:
    class: UBC\SISAPI\Serializer\JMSSerializer

  sisapi.rpc_client:
    class: XML_RPC_Client
    arguments: ["/auth/rpc", "%sisapi.config.service_url%"]

  sisapi.auth_module:
    class: %sisapi.auth_module.class%
    calls:
      - [setRpcClient,  ["@sisapi.rpc_client"]]
      - [setUsername, ["%sisapi.config.username%"]]
      - [setPassword, ["%sisapi.config.password%"]]
      - [setServiceApplication, ["%sisapi.config.service_application%"]]
      - [setServiceUrl, ["%sisapi.config.service_url%"]]
     # comment out below to enable basic auth
#      - [setUsername, ["%sisapi.config.username%"]]
#      - [setPassword, ["%sisapi.config.password%"]]


  sisapi.base_service:
    abstract:  true
    arguments: ["@sisapi.config", "@sisapi.http_client", "@sisapi.serializer", "@sisapi.auth_module"]

  sisapi.subject_code:
    class: UBC\SISAPI\Service\SubjectCodeService
    lazy: true
    arguments: ["@sisapi.config", "@sisapi.http_client", "@sisapi.serializer", "@sisapi.auth_module"]

  sisapi.department_code:
    class: UBC\SISAPI\Service\DepartmentCodeService
    lazy: true
    arguments: ["@sisapi.config", "@sisapi.http_client", "@sisapi.serializer", "@sisapi.auth_module"]

  sisapi.student:
    class: UBC\SISAPI\Service\StudentService
    lazy: true
    arguments: ["@sisapi.config", "@sisapi.http_client", "@sisapi.serializer", "@sisapi.auth_module"]
