language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - hhvm

before_install:
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

before_script:
 - composer install

script:
 - php php-cs-fixer.phar fix --dry-run --verbose --diff . || true;
 - vendor/bin/phpunit
